name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y gcc-aarch64-linux-gnu
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu # raspberry pi zero 2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
